### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by rorik** [wgm1001/HolaMundoTarea#7]
Falla al compilar en la linea 0, ha dejado de funcionar desde la última actualización.
Todo nuestra base de código depende de este paquete, arreglar lo antes posible por favor.

**Comment by wgm1001** [comment]
Qué esperas de un avatar de anime

**Comment by rorik** [comment]
Ya lo hemos arreglado. Gracias por nada.
Si a alguien le pasa lo mismo se puede arreglar utilizando este archivo:
[http://megaupload.com/files/32198432/fix](http://megaupload.com/files/32198432/fix)
Salu2

**Comment by wgm1001** [comment]
> Ya lo hemos arreglado. Gracias por nada.
> Si a alguien le pasa lo mismo se puede arreglar utilizando este archivo:
> http://megaupload.com/files/32198432/fix
> Salu2

El link está caído.
